# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d061ed91e7360a475771b621ebe272446279f69cca0cc208ce490ead955f56213137b5438b6d8f8ffa0e931a13d621826b8a90264d61e780700c48e1e5a90aff

test:
  secret_key_base: 3a7c91f53bf7a26e17029f19847b0ecd3fc0792c1ca9d09d005adac3afd15a62e86511eb100ddff5ad370dbbac4edd63827fea4b1fc1f139a18218f95aa40e0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
